#!/bin/bash

#check for directory existance 

if [ ! -d "./Saved_contacts" ]
  then
    mkdir Saved_contacts
fi

#function to add a new contact

add_contact () {

  echo "Please enter a name: "
  read name
  echo "Please enter an address: "
  read address
  echo "Please enter an email address: "
  read email
  echo "Please enter a phone number: "
  read phone
  echo "Name: $name Address: $address Email: $email Phone Number: $phone" > "./Saved_contacts/$name"
  echo 'Contact added and saved to a file in "Saved_contacts" directory.'
}

#function to remove a contact

remove_contact () {

  echo "Please enter the name of the contact you want to remove: "
  read name
  if [[ ! -f "$name" ]]; then
    rm "./Saved_contacts/$name"
    exit 0
  else
    echo "Contact does not exist. Try again with an existing contact name."

  fi
}

#function to display a contact

display_contact () {

  echo "please enter name of the contact : "
  read name
  if [ ! -f "$name" ]; then  
    while IFS= read -r line
      do
        echo $line
      done < "./Saved_contacts/$name"
  else
    echo "Opps!!!. Contacts does not exist in the database"
  fi

}

while getopts ":ardh" opt; do
  case ${opt} in
    a ) add_contact
      ;;
    r ) remove_contact
      ;;
    d ) display_contact
      ;;
    h ) echo "Usage = ./contacts [-a] for add contact
	   OR ./contacts [-rm] to remove a contact.
	   OR ./contacts [-d] to display a contact."
      ;;
    \? ) echo "Usage = ./contacts [-a] for add contact
           OR ./contacts [-rm] to remove a contact.
           OR ./contacts [-d] to display a contact."
      ;;
  esac
done
